In [5]:
import numpy as np
import matplotlib.pyplot as plt


ModuleNotFoundError: No module named 'matplotlib'

In [4]:
a = np.random.randn(1,3)
print(a)
print(a.shape)

[[ 0.65593358  0.14040517 -1.57969137]]
(1, 3)


In [7]:
b = np.random.randn(3,3)

In [9]:
c = a * b
print(c)
print(c.shape)

[[-0.26197302  0.02176676 -2.50436943]
 [ 0.10949449 -0.10457691 -0.47576145]
 [-1.03875004 -0.01682987  1.15360764]]
(3, 3)


In [10]:
a = np.array([[2,1], [1,3]])

print(a)
print(a.shape)
np.dot(a,a)

[[2 1]
 [1 3]]
(2, 2)


array([[ 5,  5],
       [ 5, 10]])

In [26]:
a = np.ones((3,4))
a.shape
b = np.ones((4,1))
b.shape

(4, 1)

In [19]:
for i in range(3):
    for j in range(4):
        a[i][j] = a[i][j] + 1
        
print(a)

[[3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]]


In [22]:
a*b.transpose()

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
a.transpose()*b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [27]:
np.dot(a,b)

array([[4.],
       [4.],
       [4.]])

In [28]:
a = np.array([[1,1], [1,-1]])
print(a)
print(a.shape)

[[ 1  1]
 [ 1 -1]]
(2, 2)


In [30]:
b = np.array([[2], [3]])
print(b)
print(b.shape)

[[2]
 [3]]
(2, 1)


In [31]:
a+b

array([[3, 3],
       [4, 2]])